### ISSUE TITLE
Requirement: Implement automatic annotation using YOLOV8 and SAMMED2D.

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#571] opened 2024-08-12 01:40 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Requirement: Implement automatic annotation using YOLOV8 and SAMMED2D.

### Additional

Requirement: Implement automatic annotation using YOLOV8 and SAMMED2D.

**Comment by CVHub520** [comment] 2024-08-12 01:52
Hey there! @AImagicAI,

The models you mentioned above have already been implemented. Please update your source code by running `git pull origin main` and then rerun the app.

If you encounter any issues, don't hesitate to contact me.

**Comment by CVHub520** [comment] 2024-08-12 01:52
https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/model_zoo.md

**Comment by AImagicAI** [comment] 2024-08-12 01:58
Hello, I noticed that YOLOv5 SAM and YOLOv8 EfficientViT SAM have been implemented, but I couldn't find any cases of YOLOV8 and SamMed-2d.


                       
原始邮件
                       
                     

发件人："CVHub"< ***@***.*** &gt;;

发件时间：2024/8/12 9:52

收件人："CVHub520/X-AnyLabeling"< ***@***.*** &gt;;

抄送人："AImagicAI"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [CVHub520/X-AnyLabeling] Requirement: Implement automaticannotation using YOLOV8 and SAMMED2D. (Issue #571)




 
Hey there! @AImagicAI,
 
The models you mentioned above have already been implemented. Please update your source code by running git pull origin main and then rerun the app.
 
If you encounter any issues, don't hesitate to contact me.

**Comment by AImagicAI** [comment] 2024-08-12 02:00
Hello, I noticed that YOLOv5 SAM and YOLOv8 EfficientViT SAM have been implemented, but I couldn't find any cases of YOLOV8 and SamMed-2d.

**Comment by CVHub520** [comment] 2024-08-12 13:32
Duplicate of #573.

**Closed by CVHub520** 2024-08-12 13:32 UTC
Labels: question
