### ISSUE TITLE
导出Yolo v8 obb标签问题

### ISSUE THREAD

**Issue by ZSBSB** [CVHub520/X-AnyLabeling#545] opened 2024-07-25 01:26 UTC
![image](https://github.com/user-attachments/assets/64a31bc1-a430-44b7-af92-63b029a729f3)
按理来说，导出Yolo obb标签应该是归一化0-1之间，但是如上图所示我导出的为什么还会有小于0的值？

**Comment by ZSBSB** [comment] 2024-07-25 01:45
导出的obb也有大于1的标签，正常来说这些值都是归一化后的，不应该出现大于1的情况，如下图所示为大于1的情况
![image](https://github.com/user-attachments/assets/62183cd7-5cdb-4a8f-860d-1bb39b62af1d)
我猜测大于1的情况应该是标注的时候把标签框标注到图像外面去了，也就是下图所示的情况，但是我不确定这个猜测是否正确
![image](https://github.com/user-attachments/assets/28d3b5ef-173b-451c-8e04-4e5b1d27c14a)

**Comment by CVHub520** [comment] 2024-07-25 01:46
Hi @ZSBSB 👋,

Thank you for reporting this issue. To assist you further, could you please provide the current label file along with the corresponding images and the original JSON annotations? This will help us investigate the problem in more detail.

Kindly send the requested files to our designated 📨: cv_hub@163.com.

Thank you for your cooperation! 

Best regards,  
CVHub Maintainer

**Comment by ZSBSB** [comment] 2024-07-25 01:57
> Hi @ZSBSB 👋,
> 
> Thank you for reporting this issue. To assist you further, could you please provide the current label file along with the corresponding images and the original JSON annotations? This will help us investigate the problem in more detail.
> 
> Kindly send the requested files to our designated 📨: [cv_hub@163.com](mailto:cv_hub@163.com).
> 
> Thank you for your cooperation!
> 
> Best regards, CVHub Maintainer

好的，非常感谢您的回复！

**Comment by CVHub520** [comment] 2024-07-25 02:20
I have replicated the issue and confirmed that the presence of values less than 0 and greater than 1 in the exported Yolov8-obb labels is indeed due to bounding boxes that extend beyond the boundaries of the image. This is likely caused by annotations that are made outside the image area, as you suspected. 

After further verification, it has been confirmed that YoloV8-obb training is compatible with bounding boxes that extend beyond the image boundaries. You may also try this to observe the impact on the training results. 

We look forward to your additional feedback on this matter.

**Comment by ZSBSB** [comment] 2024-07-25 02:30
> 我已经复制了这个问题，并确认导出的 Yolov8-obb 标签中存在小于 0 和大于 1 的值确实是由于边界框超出了图像的边界。正如您所怀疑的那样，这可能是由在图像区域之外进行的注释引起的。
> 
> 经过进一步验证，已经确认 YoloV8-obb 训练与延伸到图像边界之外的边界框兼容。您也可以尝试此操作来观察对训练结果的影响。
> 
> 我们期待您就此事提供更多反馈。

非常感谢您及时的回复，使我知道了出现问题的原因！

**Comment by CVHub520** [comment] 2024-07-25 02:52
@ZSBSB you're welcome! 😊 I'm thrilled that the information was beneficial to you. If you run into any snags or have further questions, please don't hesitate to get in touch.

Furthermore, if you stumble upon any specific challenges or bugs, crafting a minimal reproducible example can significantly expedite our ability to pinpoint and rectify the issue.

As a final note, ensure that you are using the most current version of the X-AnyLabeling repo to leverage the latest enhancements and bug fixes. This often helps in resolving unexpected hiccups.

Wishing you a joyful annotating adventure and the best of luck with your project! 🌟🚀

**Closed** 2024-08-08 16:39 UTC
Labels: question, Implemented
