### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/usr/lib/qt/plugins/platforms/"

### ISSUE THREAD

**Issue by Mosazh** [CVHub520/X-AnyLabeling#761] opened 2024-12-26 06:52 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

**Install X-AnyLabeling in my PC run the setup command show:**
``` shell
(x-anylabeling) MosArch% python anylabeling/app.py
2024-12-26 14:43:04,445 | INFO    | app:main:159 - 🚀 X-AnyLabeling v2.5.0 launched!
2024-12-26 14:43:04,445 | INFO    | app:main:162 - ⭐ If you like it, give us a star: https://github.com/CVHub520/X-AnyLabeling
2024-12-26 14:43:04,458 | INFO    | config:get_config:83 - 🔧 Initializing config from local file: /home/Mos/.xanylabelingrc
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/usr/lib/qt/plugins/platforms/"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs (from /usr/lib/qt/plugins/platforms/), linuxfb (from /usr/lib/qt/plugins/platforms/), minimal (from /usr/lib/qt/plugins/platforms/), minimalegl (from /usr/lib/qt/plugins/platforms/), offscreen (from /usr/lib/qt/plugins/platforms/), vnc (from /usr/lib/qt/plugins/platforms/), wayland-egl (from /usr/lib/qt/plugins/platforms/), wayland (from /usr/lib/qt/plugins/platforms/), wayland-xcomposite-egl (from /usr/lib/qt/plugins/platforms/), wayland-xcomposite-glx (from /usr/lib/qt/plugins/platforms/), xcb (from /usr/lib/qt/plugins/platforms/), linuxfb, minimal, offscreen, vnc, webgl, xcb.

zsh: IOT instruction (core dumped)  python anylabeling/app.py
```

**and then I cat the  /usr/lib/qt/plugins/platforms/ dicstory:**
``` shell
(x-anylabeling) MosArch% ls /usr/lib/qt/plugins/platforms
libqeglfs.so    libqminimalegl.so  libqoffscreen.so  libqwayland-egl.so      libqwayland-xcomposite-egl.so  libqxcb.so
libqlinuxfb.so  libqminimal.so     libqvnc.so        libqwayland-generic.so  libqwayland-xcomposite-glx.so
```
the qt plugin exist in QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins/platforms/

**my envi info**
``` shell
(x-anylabeling) MosArch% python anylabeling/checks.py 
Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.5.0', 'Device': 'CPU'}

System Information:
    {'CPU': '',
     'CUDA': None,
     'GPU': None,
     'Operating System': 'Linux-6.12.6-arch1-1-x86_64-with-glibc2.40',
     'Python Version': '3.9.21'}

Package Information:
    {'ONNX Runtime GPU Version': None,
     'ONNX Runtime Version': '1.19.2',
     'ONNX Version': '1.17.0',
     'OpenCV Contrib Python Headless Version': '4.10.0.84',
     'PyQt5 Version': '5.15.7'}
```

**Comment by CVHub520** [comment] 2024-12-26 06:56
Duplicate of #586, #569, #541, #370.

**Closed by CVHub520** 2024-12-26 06:56 UTC
Labels: question

**Comment by Mosazh** [comment] 2024-12-26 07:14
> Duplicate of #586, #569, #541, #370.重复的 #586 ， #569 ， #541 ， #370 。

I exec sudo pacman -S qt5-wayland to reinstall qt5wayland before commit issue, and in my .zshrc I set `export QT_QPA_PLATFORM=wayland` and `export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins/platforms/`

I still looking a workaround

**Comment by Mosazh** [comment] 2024-12-26 07:34
I adjust the zshrc config to `QT_QPA_PLATFORM="wayland;xcb"`, allows Qt to use the xcb (X11) plugin instead if Wayland is not available. Use the way can solve the probielm temporarily ,but icon button zoom ratio error by this workaround.
![2024-12-26_15-31](https://github.com/user-attachments/assets/ec5e96cd-752b-49fe-b99b-c9fdcaf25009)

**Comment by CVHub520** [comment] 2024-12-26 07:46
Thanks for sharing.

The core issue is might related to `Wayland's` handling of window management, particularly with borderless windows in Qt applications. Here's some advises you can try it out:

1. set QApplication initialization:

```bash
export QT_QPA_PLATFORM=xcb
```

This forces the application to use XCB (X11) instead of Wayland.

**Comment by Mosazh** [comment] 2024-12-26 07:50
> Thanks for sharing.  感谢分享。
> 
> The core issue is might related to `Wayland's` handling of window management, particularly with borderless windows in Qt applications. Here's some advises you can try it out:核心问题可能与窗口管理中的 `Wayland's` 处理有关，尤其是在 Qt 应用程序的无边框窗口中。以下是一些建议您可以尝试：
> 
> 1. set QApplication initialization:设置 QApplication 初始化：
> 
> ```shell
> export QT_QPA_PLATFORM=xcb
> ```
> 
> This forces the application to use XCB (X11) instead of Wayland.这强制应用程序使用 XCB（X11）而不是 Wayland。

Yes, I konw ,the `QT_QPA_PLATFORM="wayland;xcb"`, allows Qt to use the xcb (X11) plugin instead if Wayland is not available.

**Comment by CVHub520** [comment] 2024-12-26 07:52
You should disable Wayland.
