### ISSUE TITLE
Microsoft Florence-2

### ISSUE THREAD

**Issue by R3xpook** [CVHub520/X-AnyLabeling#616] opened 2024-09-05 22:08 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

Add support for florence-2 and custom finetuned models

### Use case

Florence-2 supports object detection, regional proposal , ocr , ocr with bbox and much more

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment] 2024-09-06 03:36
Hello! I see that you've opened an issue regarding adding support for Microsoft Florence-2 and custom finetuned models in X-AnyLabeling.

As per your request, I'll make sure to include this feature in my development schedule. If you have any further questions or concerns, please don't hesitate to ask. We're always here to help! 🤗✨

**Comment by CVHub520** [comment] 2024-12-04 16:48
Duplicate of #679

**Closed by CVHub520** 2024-12-04 16:48 UTC
Labels: enhancement, Planned
