### ISSUE TITLE
属性编辑的问题

### ISSUE THREAD

**Issue by Sean27oz** [CVHub520/X-AnyLabeling#132] opened 2023-11-29 10:09 UTC
我的操作步骤如下：
打开一包图像数据 -> 导入按要求整理的属性json文件 -> 开始标注矩形框 -> 快捷键CTRL+J编辑矩形框 -> 编辑2个框的属性一直是一致的，无法根据实际情况进行更改。

不知道是不是我操作有问题，还是程序bug，麻烦回复下，谢谢~

**Comment by Sean27oz** [comment] 2023-11-29 10:27
![VeryCapture_20231129182718](https://github.com/CVHub520/X-AnyLabeling/assets/121592817/3d2fcd07-eb54-4eb9-83ff-5f9aab0215f8)

**Comment by CVHub520** [comment] 2023-11-29 14:47
Hello, @Sean27oz:

Thank you for reaching out. To edit the attributes of a bounding box, you need to first select the box by clicking on it. Once the box is selected, you can edit the attributes. Please ensure that the bounding box is highlighted/selected before attempting to modify its properties.

If you have any more questions or encounter further issues, feel free to ask for assistance.

Best regards,
CVHub

**Comment by CVHub520** [comment] 2023-11-30 06:18
Hi, thank you for your feedback. I will review it later. Please be patient for my response.

**Comment by zhangpzh** [comment] 2023-12-04 10:44
Hello, its Dec 4. I also encounter similar issues in attribute editing as @Sean27oz did. I am using the Linux release GPU on Ubuntu 20.04LTS. I consider there exists logic bug in the attribute editing module. And I think by default checked multiple objects design is awful. And I think the blue row highlight should be consistent with the checkbox tick (that is unified into one).

**Comment by CVHub520** [comment] 2023-12-04 14:56
> Hello, its Dec 4 (just wanna say the bug still exists). I also encounter similar issues in attribute editing as @Sean27oz did. I am using the Linux release GPU on Ubuntu 20.04LTS. I consider there exists logic bug in the attribute editing module. And I think the design that "once the user jump into the editing mode by Ctrl+j, all objects' checked boxes are ticked" is awful. Especially, the blue row highlight selection is disentangled with the checkbox ticking (they had better be unified into one for user experience since users are easily confused by this). ![image](https://private-user-images.githubusercontent.com/8026540/287672365-c8e0bad0-284c-4ccd-b198-9b7001cf1d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDIwMzAsIm5iZiI6MTcwMTcwMTczMCwicGF0aCI6Ii84MDI2NTQwLzI4NzY3MjM2NS1jOGUwYmFkMC0yODRjLTRjY2QtYjE5OC05YjcwMDFjZjFkNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTQ1NTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM3YTBlNThmMzBkNjQyYmYwM2YxMWU3Mjg2YmRjOTI2MGM1OWMwNTgzMDA0MDU5Njg0YzEyMDk3YjljYThhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w2WkyUmSR5r8lBNYPCmDvGqBoLIgmGHw9iEAi2StW64)
> 
> Let me keep describing the bug I met during attribute editing. It is convenient to first annotate several object by bounding box mode. Then I apply Ctrl+j to shift to attribute editing mode. In case of misoperation, I have been trying carefully editing each object attribute at each time by simultaneously blue-highlight it and tick it, and assign it an attribute by selecting in the predefined list (Before assigning attribute of the next object, I untick the previous one, blue-highlight the new object, tick the new object). After finishing assigning attributes to all objects in current frame, I click the '->' arrow to the next image. After that,I turn back by '<-' to examine attributes of the last image. I find that only one object possesses exactly the attribute I have tagged before, leaving the other objects being set to the default attribute (The default attribute is the first in the option list a.k.a. the first in the json file we user specify). I think this behavior might due to some unexpected short-cut attribute inheritance bug that is first designed for certain convenient usage but currently it becomes a bug. Looking forward to your solution.

Duplicate of #135.

**Closed** 2023-12-12 02:57 UTC
Labels: bug, question
