### ISSUE TITLE
Onnxruntime模型卸载没有释放显存

### ISSUE THREAD

**Issue by panp4n** [CVHub520/X-AnyLabeling#735] opened 2024-12-10 09:05 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

版本2.4.4，使用Onnxruntime-gpu1.18.1加载模型。
调用unload函数无法完全释放显存。请问有没有办法在不关闭软件的情况下完全释放模型占用的显存

**Comment by CVHub520** [comment] 2024-12-10 09:27
Hey there! @panp4n,

Thank you for raising this issue. Unfortunately, there is currently no reliable method to fully release GPU memory after unloading an ONNX model when using `onnxruntime-gpu`. This is a known limitation of the ONNX Runtime framework itself.

I recommend reaching out to the ONNX Runtime community for further assistance, as they may provide better insights or potential workarounds for your use case. You can check their [GitHub repository](https://github.com/microsoft/onnxruntime) or forums for support. As an alternative way, we recommend you use the pytorch/tensorrt/openvino or other backends for inferencing. For more details, you can take this [example](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/services/auto_labeling/florence2.py) as guidance.

Let us know if you have additional questions or suggestions!

**Comment by CVHub520** [comment] 2024-12-11 03:39
Duplicate of #343

**Closed by CVHub520** 2024-12-11 03:39 UTC
Labels: help wanted, question
