### ISSUE TITLE
export question

### ISSUE THREAD

**Issue by ZixinxinWang** [CVHub520/X-AnyLabeling#642] opened 2024-09-22 10:15 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

![1727000011600](https://github.com/user-attachments/assets/abad9f72-91ae-400c-b969-0362c1f413e9)
当我导出mask标签的时候，我遇到了这样的问题：
导出标签时发生错误：“image_width”
请问可能时什么原因？

**Comment by ZixinxinWang** [comment] 2024-09-22 10:18
![Uploading 1727000011600.png…]()

**Comment by CVHub520** [comment] 2024-09-22 10:43
Hey there! 🌟

I'm sorry to hear about the trouble you're having with exporting masks. The error message "imageWidth" seems to indicate a problem with the image dimensions specified in your JSON file, though the provided JSON appears to have all necessary fields correctly populated.

Please compress your  image file along with annotated JSON file into a single ZIP archive. Once prepared, kindly attach the ZIP file to an email and send it to: [cv_hub@163.com](mailto:cv_hub@163.com). Your prompt assistance is greatly appreciated. Thank you in advance for your cooperation.

**Comment by CVHub520** [comment] 2024-11-01 10:06
Duplicate of #477 .

**Closed by CVHub520** 2024-11-01 10:06 UTC
Labels: question
