### ISSUE TITLE
track的时候有的物体无法识别，能否标注出来让模型后续继续跟踪

### ISSUE THREAD

**Issue by Chenjixuanstu** [CVHub520/X-AnyLabeling#532] opened 2024-07-18 04:45 UTC

**Comment by CVHub520** [comment] 2024-07-18 05:41
This feature is currently not available. Please stay tuned for future updates.

**Comment by CVHub520** [comment] 2024-08-08 16:45
Duplicate of #421.

**Closed by CVHub520** 2024-08-08 16:45 UTC
Labels: enhancement
