### ISSUE TITLE
A problem when using sam2 video model（about cuda or cpu）

### ISSUE THREAD

**Issue by flvra** [CVHub520/X-AnyLabeling#719] opened 2024-11-26 13:08 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

Hello！Here is the question:When I use Sam video model with cpu,it works right.But after I install pytorch(right version pytorch2.3.1&torch version 0.18.1),the model can't show any result in the pretained frames.And the terminal didn't tell me any error about it,I wonder why.

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.4.4', 'Device': 'CPU'}

System Information:
    {'CPU': 'AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD',
     'CUDA': None,
     'GPU': '0, NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096',
     'Operating System': 'Windows-10-10.0.22631-SP0',
     'Python Version': '3.10.15'}

Package Information:
    {'ONNX Runtime GPU Version': None,
     'ONNX Runtime Version': '1.20.1',
     'ONNX Version': '1.17.0',
     'OpenCV Contrib Python Headless Version': '4.10.0.84',
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

none

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment] 2024-11-26 15:06
Hi there, thanks for reporting this problem with the Sam2 video model. It sounds like you're running into an issue where the model isn't displaying any results after installing the PyTorch version you mentioned.

A few questions that could help me better understand the problem:
- Could you provide more details on the specific error or behavior you're seeing? For example, are you getting any messages or just no output at all?
- Are there any other system details or environmental factors that could be relevant, like your OS, GPU hardware, etc.?

I'm happy to work through this with you, but I'll need a bit more information to better diagnose the problem. Once I have those details, I can try to provide some suggestions on how to troubleshoot and resolve the issue. Please let me know what else you can share, and I'll do my best to help!

**Comment by flvra** [comment] 2024-11-26 16:36
I got no any message,just no output in the following frames,I'm using win11,and my Graphics card is 3050ti 4g（also test on 3060ti 12g,but the same problem）;
my torchversion:
torch                          2.3.1+cu118
torchaudio                     2.3.1+cu118
torchvision                    0.18.1+cu118
my anylabeling version: __version__ = "2.4.4"

**Comment by CVHub520** [comment] 2024-11-26 16:55
The issue you're facing with the Sam2 video model not showing any output seems to be related to your setup. The first thing I would suggest is to double-check that you have installed all the required dependencies correctly, including the specific versions of PyTorch, CUDA, and other libraries mentioned in the Sam2 model's requirements.

Could you please try running the sample scripts or notebooks provided in the [Sam2](https://github.com/facebookresearch/sam2) repository? That would help you determine if the issue is with your specific setup or the model itself.

The key is to ensure your environment is set up correctly. Once we've verified that, we can dive deeper into any specific problems you're facing. Let me know if you have any other questions!

**Comment by flvra** [comment] 2024-11-27 06:53
I get an error like this:
2024-11-27 14:52:39,309 | WARNING | segment_anything_2_video:predict_shapes:456 - cannot import name '_C' from 'sam2' (/home/ras/segment-anything-2/sam2/__init__.py)
Traceback (most recent call last):
  File "/home/ras/X-AnyLabeling/./anylabeling/services/auto_labeling/segment_anything_2_video.py", line 449, in predict_shapes
    shapes, replace = self.video_process(cv_image, filename)
  File "/home/ras/X-AnyLabeling/./anylabeling/services/auto_labeling/segment_anything_2_video.py", line 409, in video_process
    ) = self.video_predictor.add_new_prompt(
  File "/home/ras/miniconda3/envs/label/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ras/segment-anything-2/sam2/sam2_camera_predictor.py", line 274, in add_new_prompt
    current_out, _ = self._run_single_frame_inference(
  File "/home/ras/segment-anything-2/sam2/sam2_camera_predictor.py", line 990, in _run_single_frame_inference
    pred_masks_gpu = fill_holes_in_mask_scores(
  File "/home/ras/segment-anything-2/sam2/utils/misc.py", line 238, in fill_holes_in_mask_scores
    labels, areas = get_connected_components(mask <= 0)
  File "/home/ras/segment-anything-2/sam2/utils/misc.py", line 61, in get_connected_components
    from sam2 import _C
ImportError: cannot import name '_C' from 'sam2' (/home/ras/segment-anything-2/sam2/__init__.py)

**Comment by CVHub520** [comment] 2024-11-27 07:04
Duplicate of #613

**Comment by flvra** [comment] 2024-11-27 07:04
I have solve this from[https://github.com/CVHub520/X-AnyLabeling/issues/613](url),it's the problem with the setup of sam2, many thanks to your solution!

**Closed by CVHub520** 2024-11-27 07:04 UTC
Labels: bug

**Comment by CVHub520** [comment] 2024-11-27 07:07
> I have solve this from[https://github.com/CVHub520/X-AnyLabeling/issues/613](url),it's the problem with the setup of sam2, many thanks to your solution!

Glad to hear you found a solution! Thanks for the update.
