### ISSUE TITLE
是否支持网页端？

### ISSUE THREAD

**Issue by 997897336** [CVHub520/X-AnyLabeling#710] opened 2024-11-13 09:04 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

希望能部署到网页端

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment] 2024-11-13 09:05
Duplicate of #253

**Closed** 2024-12-10 08:04 UTC
Labels: duplicate, enhancement, help wanted
