### ISSUE TITLE
删除图像时卡死闪退

### ISSUE THREAD

**Issue by Zomcxj** [CVHub520/X-AnyLabeling#601] opened 2024-08-27 06:58 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

删除图像时卡死闪退

**Comment by CVHub520** [comment] 2024-08-27 07:12
Hello, @Zomcxj,

Thank you for reporting the issue of freezing and crashing when deleting images. We apologize for any inconvenience this may have caused you.

To assist us in resolving this issue, we would appreciate it if you could provide the following additional information:

- Which version of the software are you using?
- Could you describe the specific steps you took when deleting the images?
- Did the software exhibit any other abnormal behavior before the deletion attempt?

If possible, could you attach the error log or crash report?

Please note that the image deletion feature is currently experimental and we strongly advise against using it directly through the interface. If you need to delete images, we recommend using alternative methods that are more stable.

To help us reproduce the issue, could you provide a detailed list of steps that lead to the freezing and crashing? This will greatly aid us in diagnosing and fixing the problem.

**Comment by Zomcxj** [comment] 2024-08-27 07:19
2.4.0中出现删除图像，标签卡死闪退，2.3.6没有这个问题

**Comment by Zomcxj** [comment] 2024-08-29 01:31
按正常速度 弹出确认删除图像窗口再enter删除不会闪退  如果窗口没有完全弹出就按enter则会卡退（2.3.6就不会卡退） 应该和2.3.6有些区别

**Comment by CVHub520** [comment] 2024-08-29 02:16
> 按正常速度 弹出确认删除图像窗口再enter删除不会闪退 如果窗口没有完全弹出就按enter则会卡退（2.3.6就不会卡退） 应该和2.3.6有些区别

Thank you for bringing this to our attention. I will review the report in detail later.

**Comment by CVHub520** [comment] 2024-08-30 02:41
Hello there,

We appreciate your detailed report regarding the application's behavior. We understand that when attempting to delete an image, if the confirmation dialog is not fully displayed and the Enter key is pressed, it leads to a crash.

Now, we has taken this issue seriously and is currently investigating the root cause. We are committed to delivering a robust and reliable user experience. We will ensure that the application is enhanced to handle user inputs more gracefully, even when they are made in quick succession.

We value your feedback and it's through such reports that we can continue to refine our software. If you encounter any further issues or have additional comments, please feel free to reach out. Your satisfaction is our top priority.

**Closed** 2024-08-30 13:52 UTC
Labels: question, Fixed
