### ISSUE TITLE
ai自动标注切换模型后不会清理内存

### ISSUE THREAD

**Issue by panda2830** [CVHub520/X-AnyLabeling#549] opened 2024-07-26 16:38 UTC
打开图片目录后并开启ai自动标注再进行切换模型后之前的模型还会一直占用内存直到内存耗尽报错
![2](https://github.com/user-attachments/assets/1f508867-c967-47e6-9190-fe212e16aaef)
![1](https://github.com/user-attachments/assets/09f97ddb-2006-468d-b711-f6c1f0cd58ad)

**Comment by CVHub520** [comment] 2024-07-27 08:12
Hello @panda2830 👋,

Thank you for reporting this issue. It seems you've encountered a problem with memory not being released after switching models in the AI auto-labeling feature. To better understand and replicate the issue, could you please provide a detailed step-by-step guide on how you're interacting with the software? Specifically, what sequence of actions are you taking before you notice the memory issue?

This information will help us reproduce the issue and work on a fix. Also, if you could mention the models you are switching between and any error messages you receive, that would be very helpful.

Looking forward to your response!

Best regards,
CVHub Maintainer

**Comment by 1zero224** [comment] 2024-08-28 17:46
从 GUI 运行的cpu版本也遇到了这个问题，随着标记图片的增多，图片缓存似乎没有清理，即使没有开启ai模型标注，采用手动标注，内存占用也在不断增大
![PixPin_2024-08-29_01-44-16](https://github.com/user-attachments/assets/1cbe7fde-6c74-421d-bfc4-53bd103fb050)

**Comment by CVHub520** [comment] 2024-08-29 02:04
> 从 GUI 运行的cpu版本也遇到了这个问题，随着标记图片的增多，图片缓存似乎没有清理，即使没有开启ai模型标注，采用手动标注，内存占用也在不断增大 ![PixPin_2024-08-29_01-44-16](https://private-user-images.githubusercontent.com/94456849/362396553-1cbe7fde-6c74-421d-bfc4-53bd103fb050.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTczNTMsIm5iZiI6MTcyNDg5NzA1MywicGF0aCI6Ii85NDQ1Njg0OS8zNjIzOTY1NTMtMWNiZTdmZGUtNmM3NC00MjFkLWJmYzQtNTNiZDEwM2ZiMDUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZDhjYjMxZmRkYzlkZDAwZWZlZWExZDM3OWIxNmFkMGQ4MDEzZDkyMGRkYzlmNGI1NWFkMjRiYmZkMmYwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrDYl4lLoy0PoIUnFLorVSyFwdJ_kHDsFS3bKtqyQ08)

Duplicate of #600

**Comment by CVHub520** [comment] 2024-08-29 07:31
Fixed. @panda2830, @1zero224

**Closed** 2024-09-03 14:35 UTC
Labels: bug, invalid, Fixed
