### ISSUE TITLE
导入自定义模型的时候报错

### ISSUE THREAD

**Issue by zhaohuchang** [CVHub520/X-AnyLabeling#424] opened 2024-05-19 09:20 UTC
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

**Comment by zhaohuchang** [comment] 2024-05-19 09:23
![360截图20240519172243](https://github.com/CVHub520/X-AnyLabeling/assets/112373995/fc67d008-79e0-4b5c-8e79-3132af91fe28)
好像是使用所有的模型都报这个错误

**Comment by CVHub520** [comment] 2024-05-20 02:03
Duplicate of #359.

**Comment by zhaohuchang** [comment] 2024-05-20 02:03
你好。已收到你的邮件，我会尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Closed** 2024-05-20 02:03 UTC
Labels: duplicate
