### ISSUE TITLE
Error in loading model: open_vision 

### ISSUE THREAD

**Issue by ylxbyy** [CVHub520/X-AnyLabeling#740] opened 2024-12-13 03:07 UTC
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Hello~

When selecting 'open vision' as the model, an error occured in loading the model. 
![图片](https://github.com/user-attachments/assets/9f18c44d-aba0-4e45-a3f6-8c13db756b6e)

 | ERROR   | model_manager:_load_model:1103 - ❌ Error in loading model: open_vision with error: Incorrect path_or_model_id: '/home/cvhub/workspace/projects/python/multi-modal/CountGD/XGD/checkpoints/bert-base-uncased'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

However, there's a model 'open_vision_fsc147.pth' already downloaded in the 'xanylabeling_data/models/open_vision-r20241010/' folder.

How to solve this problem?

**Comment by CVHub520** [comment] 2024-12-13 03:10
Duplicate of #737

**Closed by CVHub520** 2024-12-13 03:10 UTC
Labels: question

**Comment by CVHub520** [comment] 2024-12-17 01:38
Hey @ylxbyy,

Thanks for catching that typo in the `open_vision.yaml` config!  We appreciate you taking the time to identify the incorrect path for `text_encoder_type` and updating it to the correct `bert-base-uncased`. This is now fixed, and we're all set going forward.

Your attention to detail is super helpful!

**Comment by FightingKai01** [comment] 2024-12-17 03:58
> Solved by modify the config file 'X-AnyLabeling-upn/anylabeling/configs/auto_labeling/open_vision.yaml'.
> 
> modified content: "# text_encoder_type: /home/cvhub/workspace/projects/python/multi-modal/CountGD/XGD/checkpoints/bert-base-uncased text_encoder_type: bert-base-uncased"

Hello, I have configured it according to this, and can load the model open_vision correctly, but the actual running effect cannot achieve the corresponding effect.

![problem](https://github.com/user-attachments/assets/61853afe-76a5-4180-8cb4-ef7aea55ac76)

Where does the problem come from?
