### ISSUE TITLE
SAM_Med2D现在需要每张图像点一下才能标注，如何批量自动标注

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#516] opened 2024-07-11 02:56 UTC
想修改为yolo的自动标注格式，点击批量自动标注，写死一个点作为prompt，只分割，不给标签。

**Comment by CVHub520** [comment] 2024-07-11 03:10
> 想修改为yolo的自动标注格式，点击批量自动标注，写死一个点作为prompt，只分割，不给标签。

Hey there! @AImagicAI,

Thank you for bringing this to our attention. Up until now, the auto-running mode in SAM-Med2D has not been developed. Please stay tuned for updates! Additionally, we welcome any pull requests (PRs) you might want to submit.

**Comment by CVHub520** [comment] 2024-08-08 16:48
Duplicate of #383.

**Closed by CVHub520** 2024-08-08 16:48 UTC
